<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="6" skipped="2" tests="8" time="0.764" timestamp="2022-09-01T17:43:10.951381" hostname="abigeev"><testcase classname="test_1.TestAuthApi" name="test_get_token_1" file="test_1.py" line="24" time="0.001"><failure message="AttributeError: 'TestAuthApi' object has no attribute 'api'">self = &lt;test_1.TestAuthApi testMethod=test_get_token_1&gt;

    def test_get_token_1(self):
&gt;   	response = requests.get(self.api + 'auth', json={'username': self.userLogin, 'password': self.userPassword}, headers=self.headers)
E    AttributeError: 'TestAuthApi' object has no attribute 'api'

test_1.py:26: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_2" file="test_1.py" line="30" time="0.001"><failure message="AttributeError: 'TestAuthApi' object has no attribute 'api'">self = &lt;test_1.TestAuthApi testMethod=test_get_token_2&gt;

    def test_get_token_2(self):
&gt;   	response = requests.get(self.api + 'auth', json={'username': self.userLogin, 'password': 'ASJndmfnkj'}, headers=self.headers)
E    AttributeError: 'TestAuthApi' object has no attribute 'api'

test_1.py:32: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_3" file="test_1.py" line="35" time="0.001"><failure message="AttributeError: 'TestAuthApi' object has no attribute 'api'">self = &lt;test_1.TestAuthApi testMethod=test_get_token_3&gt;

    def test_get_token_3(self):
&gt;   	response = requests.get(self.api + 'auth', json={'username': 'Ajklfdsji', 'password': 'ASJndmfnkj'}, headers=self.headers)
E    AttributeError: 'TestAuthApi' object has no attribute 'api'

test_1.py:37: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestAuthApi" name="test_get_token_4" file="test_1.py" line="40" time="0.001"><failure message="AttributeError: 'TestAuthApi' object has no attribute 'api'">self = &lt;test_1.TestAuthApi testMethod=test_get_token_4&gt;

    def test_get_token_4(self):
&gt;   	response = requests.get(self.api + 'auth', json={'username': self.userLogin}, headers=self.headers)
E    AttributeError: 'TestAuthApi' object has no attribute 'api'

test_1.py:42: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestUserApi" name="test_create_user_1" file="test_1.py" line="47" time="0.001"><skipped type="pytest.skip" message="SQL Latecy problem">D:\Programming\Python\Projects\web_scanner\web_scanner_server\test_1.py:48: SQL Latecy problem</skipped><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestUserApi" name="test_create_user_2" file="test_1.py" line="58" time="0.049"><failure message="AttributeError: 'TestUserApi' object has no attribute 'api'">self = &lt;test_1.TestUserApi testMethod=test_create_user_2&gt;

    def test_create_user_2(self):
    	db_session.global_init()
&gt;   	response = requests.post(self.api + 'user', json={
    		'token': self.adminToken,
    		'username': self.userLogin,
    		'password': 'test'}, headers=self.headers)
E    AttributeError: 'TestUserApi' object has no attribute 'api'

test_1.py:61: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestUserApi" name="test_create_user_3" file="test_1.py" line="68" time="0.001"><failure message="AttributeError: 'TestUserApi' object has no attribute 'api'">self = &lt;test_1.TestUserApi testMethod=test_create_user_3&gt;

    def test_create_user_3(self):
    	db_session.global_init()
&gt;   	response = requests.post(self.api + 'user', json={
    		'token': self.userToken,
    		'username': 'TestAccontForTest1427',
    		'password': 'test'}, headers=self.headers)
E    AttributeError: 'TestUserApi' object has no attribute 'api'

test_1.py:71: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_1.TestUserApi" name="test_delete_user_3" file="test_1.py" line="78" time="0.002"><skipped type="pytest.skip" message="SQL Latecy problem">D:\Programming\Python\Projects\web_scanner\web_scanner_server\test_1.py:79: SQL Latecy problem</skipped><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>